server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cars_spring
    username: root
    password: ${password}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true