server:
  port: 8081

spring:
  datasource:
   url: jdbc:mysql://localhost:3306
   username: root
   password: ${password}

jpa:
 hibernate:
  ddl-auto: update
  show-sql: true

appDescription: "Api_Cars"
appVersion: "1.0.0"